
---

- name: download the binary locally
  local_action get_url:
      url: "{{ item }}"
      dest: "files"
      mode: 0755
      backup: yes
  with_items:
      - "{{ gitea_download_url }}.sha256"
      - "{{ gitea_download_url }}"

- name: verify the checksum locally
  local_action shell: "sha256sum {{ gitea_source_binary }} | diff -uw - {{ gitea_source_binary }}.sha256"
  args:
    chdir: "file"
  register: download_success

- name: display the result of the previous command
  debug: var="{{ download_success }}"

- name: copy the binary over
  copy:
      src: "files/{{ gitea_source_binary }}"
      dest: "{{ gitea_install_path }}/{{ gitea_binary }}"
      owner: root
      mode: 0755
      backup: yes
  notify:
    - restart gitea
  when: "download_success.rc == 0"

#- name: copy the binary over
#command: "mv /tmp/{{ gitea_source_binary }} {{ gitea_install_path }}/{{ gitea_binary }}"
#notify:
#    - restart gitea
#when: "download_success.rc == 0"


