---

- name: create the log dir
  file:
      path: "{{ gitea_log_dir }}"
      owner: root
      mode: 0700
      state: directory


- name: create the repo dir
  file:
      path: "{{ gitea_repo_root }}"
      owner: "{{ gitea_uid }}"
      mode: 0700
      state: directory
