
---

- name: download the binary
  get_url:
      url: "{{ item }}"
      dest: "{{ gitea_download_dir }}"
      mode: 0755
      backup: yes
  with_items:
      - "{{ gitea_download_url }}.sha256"
      - "{{ gitea_download_url }}"

- name: verify the checksum
  shell: "sha256sum {{ gitea_source_binary }} | diff -uw - {{ gitea_source_binary }}.sha256"
  args:
    chdir: "{{ gitea_download_dir }}"
  register: download_success

- name: display the result of the previous command
  debug: var="{{ download_success }}"

- name: copy the binary over
  copy:
      src: "{{ gitea_download_dir }}/{{ gitea_source_binary }}"
      dest: "{{ gitea_install_path }}/{{ gitea_binary }}"
      owner: root
      mode: 0755
      remote_src: yes
      backup: yes
  notify:
    - restart gitea
  when: "download_success.rc == 0"

